name: "DavidX's Blog"
description: "Programming and more personal thoughts."

avatar: images/avatar.png
favicon: images/favicon.ico

navigation:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Tags
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  email: # someone@example.com
  github: # GitHub handle, e.g. Davidasx
  rss:  this_is_rss # nothing to change here
  # add social accounts like facebook here
  facebook: # FaceBook handle

footer-text: Copyright (c) 2024 # your name here

url: # YOUR_GITHUB_HANDLE.github.io

# do not change anything below this line

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

